### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by Zambito1** [lukepighetti/mastodon-flutter#11]
I'd like to use this project as a reference for my own, but I cannot currently do that as no license is attached. Without a license, all source code is covered by [copyright by default](https://choosealicense.com/no-permission/). I recommend adding either the GPLv3 license or the MIT license to match [mastodon_dart](https://github.com/lukepighetti/mastodon_dart)

**Comment by lukepighetti** [comment]
Closed by https://github.com/lukepighetti/mastodon_flutter/commit/39c6cf23fea1af4569310f832630e368621304e3
