### ISSUE TITLE
Discussion: AuthBuilder still necessary?

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/mastodon-flutter#8]
Does AuthBuilder even need to be a widget anymore?

It looks like it's relying on widget lifecycle methods, but it may not need to. It also looks like the majority of these methods can be private members too. You may not even need auth builder anymore since it appears that it's only submitting the clipboard code.

One option is to delete AuthBuilder, make a little AuthCodeClipboard service and hook that up to the bloc.

I have no opinion either way.

**Comment by GroovinChip** [comment]
Thanks for starting the discussion. It will be useful to have this here when I return my attention to AuthBuilder.

**Comment by GroovinChip** [comment]
I had a thought, @lukepighetti - I remember telling Simon that I want the user to have to do as little work as needed to build a Mastodon app. I think providing the AuthBuilder helps with that. Is there any reason why it wouldn't?
